  
version: "3"

networks:
  default:
    external:
      name: instrumentation-api_default

services:
  elasticmq:
    image: softwaremill/elasticmq
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
    restart: always
  instrumentation-dcs-loader:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - LOADER_POST_URL=http://instrumentation-api_api_1/instrumentation/timeseries_measurements
      - LOADER_API_KEY=appkey
      - LOADER_AWS_S3_ENDPOINT=http://minio:9000
      - LOADER_AWS_S3_DISABLE_SSL=True
      - LOADER_AWS_S3_FORCE_PATH_STYLE=True
      - LOADER_AWS_SQS_ENDPOINT=http://elasticmq:9324
      - LOADER_AWS_SQS_REGION=elasticmq
      - LOADER_AWS_SQS_QUEUE_NAME=instrumentation-dcs-goes
      - LOADER_AWS_SQS_QUEUE_URL=http://elasticmq:9324/queue/instrumentation-dcs-goes
    restart: always
